# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=200)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='diag_app.Solution')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diag_app.Tech')),
            ],
        ),
    ]
