# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 14:03
from __future__ import unicode_literals

from django.db import migrations
import csv

def load_brands(apps, schema_editor):
    with open("brand.csv", "r") as f:
        dict_reader = csv.DictReader(f, fieldnames= ['name'])
        Brand = apps.get_model("diag_app", "Brand")
        for row in dict_reader:
            brand_object = Brand(**row)
            brand_object.save()


def load_systems(apps, schema_editor):
    with open("system.csv", "r") as f:
        dict_reader = csv.DictReader(f, fieldnames= ['name'])
        System = apps.get_model("diag_app", "System")
        for row in dict_reader:
            system_object = System(**row)
            system_object.save()


def load_models(apps, schema_editor):
    with open("model.csv", "r") as f:
        dict_reader = csv.DictReader(f, fieldnames= ['brand_id','name','year'])
        Model = apps.get_model("diag_app", "Model")
        for row in dict_reader:
            model_object = Model(**row)
            model_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_brands),
        migrations.RunPython(load_systems),
        migrations.RunPython(load_models),
    ]
