# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diag_app', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='diag_app.Commit'),
        ),
        migrations.AddField(
            model_name='notification',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='diag_app.Solution'),
        ),
    ]
